### ISSUE TITLE
please make support odoo v10

### ISSUE THREAD

**Issue by putrarifin** [Fogits/survey_attachment#1]

**Comment by ivanporras** [comment]
@putrarifin  I migrate the module to odoo 10

**Comment by putrarifin** [comment]
@ivanporras can i download your module ?

**Comment by ivanporras** [comment]
@putrarifin you can see the module here https://github.com/ivanporras/survey_attachment/ ,
I did a pull request @Fogits

**Comment by putrarifin** [comment]
@ivanporras nice thanks a lot

**Comment by ivanporras** [comment]
@putrarifin I corrected some issues in version 10. You can download from my github
